name: Compile Test
on: [push, pull_request]
jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        with:
          version: "0.14.0"

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core update-index --additional-urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          arduino-cli core install "arduino:avr"
          arduino-cli core install "esp32:esp32" --additional-urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          arduino-cli lib install Ethernet
          python -m pip install --upgrade pip
          pip install pyserial
          
      - name: Arduino test
        run: |
          cp coap-simple.* ./examples/coaptest
          sed -i -e "s/XXX/10/g" ./examples/coaptest/coaptest.ino
          sed -i -e "s/<coap-simple\.h>/\"coap-simple\.h\"/g" ./examples/coaptest/coaptest.ino
          arduino-cli compile --fqbn "arduino:avr:uno" ./examples/coaptest

      - name: ESP32 test
        run: |
          cp coap-simple.* ./examples/esp32
          sed -i -e "s/<coap-simple\.h>/\"coap-simple\.h\"/g" ./examples/esp32/esp32.ino
          arduino-cli compile --fqbn "esp32:esp32:esp32" ./examples/esp32